# Generated by Django 3.2 on 2022-01-10 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainers',
            old_name='description',
            new_name='bio',
        ),
    ]
