# Generated by Django 3.2 on 2022-01-20 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaclass',
            name='class_or_product',
            field=models.CharField(default='class', max_length=7),
            preserve_default=False,
        ),
    ]
