# Generated by Django 3.2 on 2022-01-22 16:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0002_yogaclass_class_or_product'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yogaclass',
            old_name='class_or_product',
            new_name='category',
        ),
    ]
