# Generated by Django 3.2 on 2022-01-23 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0003_rename_class_or_product_yogaclass_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='yogaclass',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
