# Generated by Django 3.2 on 2022-01-27 00:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_rename_trainers_trainer'),
        ('classes', '0004_yogaclass_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='category',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='equipment',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='intensity',
            field=models.CharField(choices=[(None, 'Intensity Level'), ('low', 'Low'), ('regular', 'Regular'), ('high', 'High')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='level',
            field=models.CharField(choices=[(None, 'Skill Level'), ('all', 'All'), ('beginner', 'Beginner'), ('intermediate', 'Intermediate'), ('advanced', 'Advanced')], max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='practice',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='series_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='session_duration',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='sku',
            field=models.CharField(max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='trainers.trainer'),
        ),
    ]
