# Generated by Django 3.2 on 2022-01-28 18:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0003_rename_trainers_trainer'),
        ('classes', '0005_auto_20220127_0042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='trainer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='trainers', to='trainers.trainer'),
        ),
    ]
