# Generated by Django 3.2 on 2022-01-28 21:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0006_alter_yogaclass_trainer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Practice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250, null=True)),
            ],
        ),
        migrations.AlterField(
            model_name='yogaclass',
            name='practice',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice', to='classes.practice'),
        ),
    ]
