# Generated by Django 3.2 on 2022-01-28 21:42

import classes.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0007_auto_20220128_2139'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='practice',
            field=models.CharField(max_length=250, null=True, verbose_name=classes.models.Practice),
        ),
    ]
