# Generated by Django 3.2 on 2022-01-28 22:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classes', '0008_alter_yogaclass_practice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='yogaclass',
            name='practice',
            field=models.ForeignKey(max_length=250, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='practice', to='classes.practice'),
        ),
    ]
