# Generated by Django 3.2 on 2022-01-24 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkout', '0003_auto_20220124_1449'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='classes_count',
        ),
        migrations.RemoveField(
            model_name='order',
            name='product_count',
        ),
        migrations.AddField(
            model_name='order',
            name='classes_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='products_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
