# Generated by Django 3.2 on 2022-01-19 23:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='sku',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
    ]
