# Generated by Django 3.2 on 2022-01-20 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_shopproducts_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='shopproducts',
            name='class_or_product',
            field=models.CharField(default='product', max_length=7),
            preserve_default=False,
        ),
    ]
