# Generated by Django 3.2 on 2022-01-27 00:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_rename_class_or_product_shopproducts_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shopproducts',
            name='category',
            field=models.CharField(max_length=7, null=True),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='name',
            field=models.CharField(max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='shopproducts',
            name='sku',
            field=models.CharField(max_length=254, null=True),
        ),
    ]
